---
- op: replace
  path: /spec/template/spec/sources/1/repoURL
  value: https://github.com/mshaposhnik/infra-deployments.git
- op: replace
  path: /spec/template/spec/sources/1/targetRevision
  value: preview-revert_mem_rh01
