apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- external-secrets.yaml

components:
  - ../k-components/manager-resources

helmCharts:
- name: multi-platform-controller-host-config
  releaseName: host-config
  namespace: multi-platform-controller
  repo: ../base
  valuesFile: host-values.yaml

namespace: multi-platform-controller
