apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: multi-platform-controller
resources:
  - common
  - https://github.com/mshaposhnik/multi-platform-controller/deploy/operator?ref=18fa922957b38a9bad388d736a6a9505215be8c6
  - https://github.com/mshaposhnik/multi-platform-controller/deploy/otp?ref=18fa922957b38a9bad388d736a6a9505215be8c6
images:
  - name: multi-platform-controller
    newName: quay.io/mshaposhnik/multi-platform-controller
    newTag: dev
  - name: multi-platform-otp-server
    newName: quay.io/konflux-ci/multi-platform-controller-otp-service
    newTag: ec950d0cfb87bcfd6e3a79fc2b5ee40989126123
