apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: multi-platform-controller

resources:
- ../base
- host-config.yaml
- external-secrets.yaml

# temporary patch to use the latest image
patches:
- path: controller-image-patch.yaml
